server:
  port: 8761

eureka:
  environment: xzhTest
  instance:
    hostname: localhost
    appname: Eureka-Server
  client:
    register-with-eureka: true  # 单点的时候设置为 false 禁止注册自身
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8763/eureka/
  replication