server:
  port: 8761

eureka:
  environment: dev
  server:
    # 是否允许开启自我保护模式，缺省：true
    # 当Eureka服务器在短时间内丢失过多客户端时，自我保护模式可使服务端不再删除失去连接的客户端
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 500 #clean interval  # Eureka服务器清理无效节点的时间间隔，单位：毫秒，缺省：60000，即60秒
    response-cache-update-interval-ms: 1000
    peer-eureka-nodes-update-interval-ms: 5000 # Peer节点更新间隔，单位：毫秒
  instance:

    #搭建集群的时候,spring.application.name必须相同，eureka.instance.hostname必须不同，否则都会失败
    hostname: localhost-01  # 应用实例主机名,prefer-ip-address = true，hostname将失效
    appname: Eureka-Server  # 服务名，默认取 spring.application.name 配置值，如果没有则为 unknown
    instance-id: ${eureka.instance.appname}-peer01:${server.port} # 实例ID
    prefer-ip-address: false  # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    lease-expiration-duration-in-seconds: 1  # 服务失效时间，失效的服务将被剔除。单位：秒，默认：90
    lease-renewal-interval-in-seconds: 30 # 服务续约（心跳）频率，单位：秒，缺省30
    status-page-url-path: /info # 状态页面的URL，相对路径，默认使用 HTTP 访问，如需使用 HTTPS则要使用绝对路径配置，缺省：/info
    health-check-url-path: /health  # 健康检查页面的URL，相对路径，默认使用 HTTP 访问，如需使用 HTTPS则要使用绝对路径配置，缺省：/health
#    ip-address: test
  client:
    register-with-eureka: false  # 单点的时候设置为 false 禁止注册自身
    fetch-registry: false #是否从Eureka获取注册信息，缺省：true,一般情况下，Eureka服务端是不需要的
#    service-url:
      # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
      # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
#      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
    registry-fetch-interval-seconds: 30 # 客户端拉取服务注册信息间隔，单位：秒，缺省：30